version: "3.0"
services:
  db:
    image: postgres:alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD:
      POSTGRES_DB: homesearch
      PGDATA: /data
    volumes:
      - postgres_data:/data
  frontend:
    build:
      context: .
      dockerfile: ./docker/FrontEndDockerfile
    restart: always
    ports:
      - "5001:5001"
    environment:
      - GOOGLEMAPSAPIKEY
  backend:
    build:
      context: .
      dockerfile: ./docker/BackEndDockerfile
    depends_on:
      - db
    restart: always
    ports:
      - "80:80"
    environment:
      - GOOGLEMAPSAPIKEY
      - ZOOPLAAPIKEY
      - POSTGRES_PASSWORD
volumes:
  postgres_data:
