version: "0.1"
services:
  db:
    image: postgres:alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD:
      POSTGRES_DB: homesearch
      PGDATA: /data
    volumes:
      - postgres_data:/data
  frontend:
    build:
      context: .
      dockerfile: ./docker/FrontEndDockerfile
    restart: always
    ports:
      - "5001:5001"
    args:
      URL_API: $URL_API
    environment:
      - GOOGLEMAPSAPIKEY
      - PORT=5001
      - CLIENT_ID
  backend:
    build:
      context: .
      dockerfile: ./docker/BackEndDockerfile
    depends_on:
      - db
    restart: always
    ports:
      - "80:80"
    environment:
      - GOOGLEMAPSAPIKEY
      - ZOOPLAAPIKEY
      - POSTGRES_PASSWORD
      - PORT=80
      - CLIENT_ID
      - SECRET_KEY
volumes:
  postgres_data:
