version: "3.0"
services:
  frontend:
    build:
      context: .
      dockerfile: ./docker/FrontEndDockerfile
    restart: always
    ports:
      - "5001:5001"
    environment:
      - GOOGLEMAPSAPIKEY
  backend:
    build:
      context: .
      dockerfile: ./docker/BackEndDockerfile
    ports:
      - "80:80"
    environment:
      - GOOGLEMAPSAPIKEY
      - ZOOPLAAPIKEY
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"