version: "3.0"
services:
  frontend:
    build:
      context: .
      dockerfile: ./docker/FrontEndDockerfile
    restart: always
    ports:
      - "5001:5001"
    environment:
      - GOOGLEMAPSAPIKEY
  backend:
    build:
      context: .
      dockerfile: ./docker/BackEndDockerfile
    restart: always
    ports:
      - "80:80"
    environment:
      - GOOGLEMAPSAPIKEY
      - ZOOPLAAPIKEY
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
  database:
    build:
      context: .
      dockerfile: ./docker/DatabaseDockerfile
    ports:
      - 5432:5432
    volumes:
      - database-data:/data
volumes:
  redis_data:
  database-data: